### ISSUE TITLE
Provide a way to set the initial extent of a map.

### ISSUE THREAD

**Issue by coolkang** [4kmapping/4kadopt_server#4]
In URL, how about putting variables (min_x, min_y, max_x, max_y) and if a browser see the values, it zoom into the boundary.

This will be useful to provide pre-defined zoomed-in maps for Singapore event.

**Comment by joshuadelange** [comment]
Implemented!

Example;
`http://localhost:8000/#lat=52.3667&lon=4.9000&zoom=7` for NL focussed map

Recommended way to get this info;
- Move and zoom map to desirable state
- Open JS console
- Use `window.ozController.map.getCenter()` and `window.ozController.map.getZoom()`

**Comment by coolkang** [comment]
When I use the URL patterns, it does not show adopted OZ information.
